corr_map function docstring v0.1
UBC-MDS/simpler_eda pull request #13
Opened 2021-02-26 20:10 UTC by ChuckHo777

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +def corr_map(path, data_type, features, sep=",", color_theme='yellowgreenblue', plot_width=400, plot_height=300, title="Correlation Map"):
1. removing "reading dataset"
2. color_theme : str, optional
3. "Plot a correlation map for the given list of features. Users can also set multiple arguments regarding the data (e.g. the separator) and the setting for the correlation plot from colour schemes, plot width, height and plot title.

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    path: str
remove path

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    color_theme: str, default='yellowgreenblue'
color_scheme

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +      Other proper color scheme reference can be found inhttps://vega.github.io/vega/docs/schemes/
```suggestion
      Other proper colour scheme reference can be found in https://vega.github.io/vega/docs/schemes/
```

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    >>> from corr_map import corr_map
from simpler_eda.corr_map import corr_map

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    >>> import altair as alt
add:
import numpy as np

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    >>> corr_map.corr_map("data/abc.csv", "csv", ["age", "height", "income"])
remove "corr_map."

2021-02-26 23:15 UTC, nichowu commented on simpler_eda/corr_map.py
> +    An altair.vegalite.v4.api.Chart object
Returns: chart: Chart object altair.vegalite.v4.api.Chart
                The altair Chart object build from the specification

2021-02-26 23:17 UTC, ChuckHo777 commented on simpler_eda/corr_map.py
> +      Other proper color scheme reference can be found inhttps://vega.github.io/vega/docs/schemes/
As discussed, I will edit all comments in one go and PR again while color should be kept as color.

2021-02-26 23:50 UTC, ChuckHo777 commented on simpler_eda/corr_map.py
> +    An altair.vegalite.v4.api.Chart object
As discussed, let's keep the example ending with calling the function.

2021-02-27 01:10 UTC, nichowu requested changes
2 changes requested.

2021-02-27 01:10 UTC, nichowu commented on simpler_eda/corr_map.py
> +  altair.vegalite.v4.api.Chart
change to:

Returns
--------
`altair`
The altair correlation map plot

2021-02-27 01:10 UTC, nichowu commented on simpler_eda/corr_map.py
> +  Users are allow to set multiple arguments regarding the setting of the correlation plot
Users are **_allowed_** to set multiple arguments regarding the setting of the correlation plot **_including_** color schemes, plot width, height and plot title.

2021-02-27 05:38 UTC, nichowu approved these changes

2021-02-27 05:43 UTC, merged